### ISSUE TITLE
RAVE models have delay at 2048 @ 48k

### ISSUE THREAD

**Issue by christhetree** [QosmoInc/neutone_sdk#23]
This delay can be heard when wet is at 0 and dry is at 100 with the buddhist chant model. A temporary fix is using 1024 @ 48k.

I believe this bug is related to the warmup cycles and the difficulty we have in getting the first buffer to come out without delay. Will need to be fixed in the VST most likely.

cc: @lewiswolf who reported this issue

**Comment by lewiswolf** [comment]
Thanks for taking a look at this! :)

**Comment by christhetree** [comment]
Should be fixed with 1.4.0 plugin.
