### ISSUE TITLE
[MODEL] NeuraFuzz

### ISSUE THREAD

**Issue by mcomunita** [QosmoInc/neutone_sdk#29]
## A brief description of what your model does

Neural fuzz distortion trained on an analogue fuzz circuit I designed + DSP ring modulator. Designed mainly for guitar.

## Checklist
- [x] I have checked the model works properly loaded locally in the Neutone plugin on my machine. MacOS Ventura 13.0.1, Reaper 6.75, Intel
- [x] I have uploaded the .nm model file at a publicly available location: https://github.com/mcomunita/neurafuzz/blob/master/export_model/model_fuzzring_v1.0.0.nm

## Extra information
<Any other extra information you'd like to tell us>

## Metadata

The model export function should dump a json file. Please paste the contents here for review and discussions.

```
{
    "model_name": "NeuraFuzz",
    "model_authors": [
        "Marco Comunit\u00e0"
    ],
    "model_version": "1.0.0",
    "model_short_description": "Neural fuzz + Ring modulator",
    "model_long_description": "Neural fuzz distortion trained on an analogue fuzz circuit I designed + DSP ring modulator to add extra oomph",
    "technical_description": "This neural fuzz was designed firstly as an analogue circuit. Training data was generated from Spice circuit simulation and used to train a gated convolution network with temporal film modulation. Designed mainly for guitar",
    "technical_links": {
        "Paper": "https://arxiv.org/abs/2211.00497",
        "Code": "https://github.com/mcomunita/gcn-tfilm",
        "Website": "https://mcomunita.github.io/gcn-tfilm_page"
    },
    "tags": [
        "fuzz",
        "distortion",
        "overdrive"
    ],
    "citation": "Comunit{\\`a}, M. et al (2022). Modelling black-box audio effects with time-varying feature modulation. arXiv preprint arXiv:2211.00497.",
    "is_experimental": false,
    "neutone_parameters": {
        "p1": {
            "name": "GAIN",
            "description": "gain",
            "type": "knob",
            "used": "True",
            "default_value": "0.1"
        },
        "p2": {
            "name": "FUZZ",
            "description": "fuzz",
            "type": "knob",
            "used": "True",
            "default_value": "0.5"
        },
        "p3": {
            "name": "RING",
            "description": "fuzz/ring mod mix",
            "type": "knob",
            "used": "True",
            "default_value": "0.0"
        },
        "p4": {
            "name": "FREQ",
            "description": "ring modulator frequency",
            "type": "knob",
            "used": "True",
            "default_value": "0.0"
        }
    },
    "wet_default_value": 1.0,
    "dry_default_value": 0.0,
    "input_gain_default_value": 0.5,
    "output_gain_default_value": 0.5,
    "is_input_mono": true,
    "is_output_mono": true,
    "model_type": "mono-mono",
    "native_sample_rates": [
        48000
    ],
    "native_buffer_sizes": [],
    "look_behind_samples": 0,
    "sdk_version": "1.1.2",
    "pytorch_version": "1.11.0",
    "date_created": 1679084952.62931
}
```

**Comment by bogdanteleaga** [comment]
Hello Marco, thank you for sending us the model! We've added it to the plugin last week before the NAMM event and tested it there as well as on our local machines and everything looks good. Please try it out yourself from the browser and let us know if you find any issues.

We can automatically update it on new releases of the SDK so you don't need to worry about that part, just let us know if you want to update the model itself sometime in the future.

**Comment by mcomunita** [comment]
Hello Bogdan, thank you for the update. The model doesn't seem to be listed on the neutone website.

**Comment by bogdanteleaga** [comment]
Indeed, the website seems to be pointing to a different collection, we were just looking into that yesterday. We'll update it for the next release! Should be coming very soon.

**Comment by bogdanteleaga** [comment]
Hello again Marco! Sorry to keep you waiting, we just released a new version of Neutone yesterday and updated the website. Your model should be up on both the plugin and the website now, let me know if you notice anything else!
