### ISSUE TITLE
Plugin support for Linux

### ISSUE THREAD

**Issue by Mec-iS** [QosmoInc/neutone_sdk#37]
Hi, thanks for your work. I know this is not SDK-related but I didn't know where to ask this question.
Is it possible for you to provide a distribution of the plugin for Linux machines? I produce music using a Linux-based (Ubuntu) workstation and it would be great to try the plugin.
Best

**Comment by bogdanteleaga** [comment]
Hello!
We usually get inquires on Discord regarding the plugin, but here is also fine, I've added a plugin label.
While it might come at a later point in the future, we haven't seen much interest in a Linux version so far and we don't have enough resources to dedicate to it in the near future.

**Comment by Mec-iS** [comment]
I understand.

According to how your build system is set up, it should be just a matter of adding a target for plugin release though (at least this is how it is for Projucer and other frameworks). Close-to-zero cost more people included.
