### ISSUE TITLE
[MODEL] RAVE.gamelan

### ISSUE THREAD

**Issue by scottyeung** [QosmoInc/neutone_sdk#60]
## A brief description of what your model does
Trained this dataset (https://zenodo.org/records/8333916) on RAVE v2, Wasserstein regularisation, I exported this model at around 2.1M steps. The result to me is quite positive. Once I fed a voice memo, the output resembles the notes played by gamelan instruments with clarity

## Checklist
- [ ] I have checked the model works properly loaded locally in the Neutone plugin on my machine. <macOS Sonoma 14.4.1, Ableton Live 11.3.13, M1 Pro>
- [ ] I have uploaded the .nm model file at a publicly available location: (https://www.dropbox.com/scl/fo/xdd6ps9pclsm9o41wm0ye/h?rlkey=v0z4ej08d35hhqbar01y8od5l&dl=0).

## Metadata

The model export function should dump a json file. Please paste the contents here for review and discussions.

```{
    "model_name": "RAVE.gamelan",
    "model_authors": [
        "Scott Yeung"
    ],
    "model_version": "1.0.0",
    "model_short_description": "RAVE model trained on Gamelan music dataset.",
    "model_long_description": "RAVE timbre transfer model trained on Gamelan music dataset.",
    "technical_description": "RAVE model proposed by Caillon, Antoine et al.",
    "technical_links": {
        "Paper": "https://arxiv.org/abs/2111.05011",
        "Code": "https://github.com/acids-ircam/RAVE"
    },
    "tags": [
        "timbre transfer",
        "RAVE"
    ],
    "citation": "Caillon, A., & Esling, P. (2021). RAVE: A variational autoencoder for fast and high-quality neural audio synthesis. arXiv preprint arXiv:2111.05011.",
    "is_experimental": true,
    "neutone_parameters": {
        "p1": {
            "name": "Chaos",
            "description": "Magnitude of latent noise",
            "type": "knob",
            "used": "True",
            "default_value": "0.0"
        },
        "p2": {
            "name": "Z edit index",
            "description": "Index of latent dimension to edit",
            "type": "knob",
            "used": "True",
            "default_value": "0.0"
        },
        "p3": {
            "name": "Z scale",
            "description": "Scale of latent variable",
            "type": "knob",
            "used": "True",
            "default_value": "0.5"
        },
        "p4": {
            "name": "Z offset",
            "description": "Offset of latent variable",
            "type": "knob",
            "used": "True",
            "default_value": "0.5"
        }
    },
    "wet_default_value": 1.0,
    "dry_default_value": 0.0,
    "input_gain_default_value": 0.5,
    "output_gain_default_value": 0.5,
    "is_input_mono": true,
    "is_output_mono": true,
    "model_type": "mono-mono",
    "native_sample_rates": [
        44100
    ],
    "native_buffer_sizes": [
        2048
    ],
    "look_behind_samples": 0,
    "sdk_version": "1.4.2",
    "pytorch_version": "2.1.1+cu121",
    "date_created": 1701004754.276784
}
```

**Comment by christhetree** [comment]
Hi Scott, thanks for submitting! We'll get back to this ASAP

**Comment by Dremor412** [comment]
is this possible tu turn Neutone model into .ts rave model ?

**Comment by christhetree** [comment]
@scottyeung we're planning on adding your model next week, thanks for your patience!

**Comment by bogdanteleaga** [comment]
@scottyeung Sorry to keep you waiting for so long. We've had a few other releases scheduled in the pipeline and did not want to stack them up too much.

Your model is now available in the plugin and on the website, please take a look and let us know if there is any problem. We will be annoucing your model on SNS soon, likely together with an upcoming minor release of the plugin.
