### ISSUE TITLE
default audio sample loading breaks on windows

### ISSUE THREAD

**Issue by sildater** [QosmoInc/neutone_sdk#67]
on windows I get the following error when exporting a model via `save_neutone_model`:
`RuntimeError: Error opening <_io.BytesIO object at 0x0000019212E07C20>: Format not recognised.`
It stems from loading the default audio mp3s in lines 129, 132, 135 in audio.py, the bytesIO object has no format and can't be read by soundfile (line 87). It works on ubuntu.

**Comment by christhetree** [comment]
@bogdanteleaga does this look familiar when you were making the audio sample changes? Perhaps there's a quick fix here

**Comment by christhetree** [comment]
@sildater thanks for raising this issue! While we look into a fix, you should still be able to export your model by setting `dump_sample=False` and `submission=False` when calling the `save_neutone_model` method.

**Comment by bogdanteleaga** [comment]
@sildater Hello! Sorry for the delay, I just tried this out on a Windows machine right now and it seems like it's working. Can you check you have the latest soundfile (I pulled 0.12.1 on a fresh install) and you can use it to read mp3 files with `soundfile.read`?

**Comment by sildater** [comment]
Hi! Thanks for the reply and sorry for the late answer! I could fix it with a fresh install of soundfile as you suggested.
